# Generated by Django 3.1.6 on 2021-03-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='summary',
        ),
    ]
