# Generated by Django 3.1.6 on 2021-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210310_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(help_text='Give a brief summary of what your post is about', max_length=500),
        ),
    ]
